import type { ProductCategory, CollectionType } from "@/types";

const COLORS = [
  { name: "Crimson", hex: "#ef4444" },
  { name: "Amber", hex: "#f59e0b" },
  { name: "Emerald", hex: "#10b981" },
  { name: "Sky", hex: "#3b82f6" },
  { name: "Violet", hex: "#8b5cf6" },
];

const SIZES = [40, 41, 42, 43, 44, 45];

export const seedProducts: Array<{
  slug: string;
  name: string;
  brand: string;
  price: number;
  img: string;
  description: string;
  category: ProductCategory;
  collection: CollectionType;
  isBestSeller: boolean;
  isNewArrival: boolean;
  colors: typeof COLORS;
  sizes: number[];
}> = [
  {
    slug: "p1",
    name: "Air M32 Pro Runner",
    brand: "Nike",
    price: 560,
    img: "/shoe-red.png",
    description: "Responsive foam cushioning with breathable knit upper for daily runs.",
    category: "male",
    collection: "running",
    isBestSeller: false,
    isNewArrival: true,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p2",
    name: "Nike Zoom Fly",
    brand: "Nike",
    price: 560,
    img: "/shoe-white.png",
    description: "Lightweight racing shoe with carbon plate for speed days.",
    category: "popular",
    collection: "running",
    isBestSeller: false,
    isNewArrival: true,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p3",
    name: "Volt Neon Racer",
    brand: "PUMA",
    price: 560,
    img: "/shoe-yellow.png",
    description: "Bold neon accents with grip-tuned rubber outsole.",
    category: "popular",
    collection: "sneaker",
    isBestSeller: false,
    isNewArrival: true,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p4",
    name: "NB Fresh Foam",
    brand: "New Balance",
    price: 560,
    img: "/shoe-green.png",
    description: "Plush Fresh Foam midsole for all-day city comfort.",
    category: "female",
    collection: "running",
    isBestSeller: false,
    isNewArrival: true,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p5",
    name: "Asics Gel Streak",
    brand: "ASICS",
    price: 480,
    img: "/shoe-green2.png",
    description: "GEL cushioning system for smooth transitions.",
    category: "male",
    collection: "running",
    isBestSeller: false,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p6",
    name: "Blaze Flame Low",
    brand: "VANS",
    price: 420,
    img: "/shoe-flame.png",
    description: "Street-ready low profile with flame-inspired colorway.",
    category: "popular",
    collection: "sneaker",
    isBestSeller: false,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p7",
    name: "Court Retro '92",
    brand: "Nike",
    price: 560,
    img: "/shoe-retro.png",
    description: "Classic court silhouette with vintage leather finish.",
    category: "male",
    collection: "sneaker",
    isBestSeller: true,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p8",
    name: "Adidas Cloudfoam",
    brand: "adidas",
    price: 390,
    img: "/adidas.png",
    description: "Cloudfoam step-in comfort for everyday wear.",
    category: "female",
    collection: "sneaker",
    isBestSeller: false,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "p9",
    name: "Hoka Volt Trail",
    brand: "HOKA",
    price: 620,
    img: "/shoe-mint.png",
    description: "Trail-ready grip with max cushioning for long hikes.",
    category: "male",
    collection: "running",
    isBestSeller: false,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "b1",
    name: "Mint Rush Pro",
    brand: "Reebok",
    price: 560,
    img: "/shoe-mint.png",
    description: "Best-selling mint colorway with pro-level support.",
    category: "popular",
    collection: "sneaker",
    isBestSeller: true,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "b2",
    name: "AeroStep Onyx",
    brand: "FILA",
    price: 560,
    img: "/shoe-red2.png",
    description: "Premium onyx black finish — our top seller this season.",
    category: "popular",
    collection: "formal",
    isBestSeller: true,
    isNewArrival: false,
    colors: COLORS,
    sizes: SIZES,
  },
  {
    slug: "c1",
    name: "Tiny Sprint Kids",
    brand: "UNDER ARMOUR",
    price: 320,
    img: "/shoe-yellow.png",
    description: "Flexible kids runner with easy slip-on design.",
    category: "children",
    collection: "running",
    isBestSeller: false,
    isNewArrival: false,
    colors: COLORS.slice(0, 3),
    sizes: [28, 29, 30, 31, 32, 33],
  },
];

export const seedReviews = [
  {
    productSlug: "p1",
    userName: "Ravi K.",
    rating: 5,
    text: "Super comfy, feels like walking on clouds. Perfect fit!",
  },
  {
    productSlug: "p2",
    userName: "Amelia S.",
    rating: 4,
    text: "Great design and quality. Runs a half size small.",
  },
  {
    productSlug: "p3",
    userName: "Jordan M.",
    rating: 5,
    text: "Bought them for daily gym use — holding up amazingly.",
  },
];
